// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pdfcompose

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PdfComposeClient is the client API for PdfCompose service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PdfComposeClient interface {
	CreatePdf(ctx context.Context, in *Upfiles, opts ...grpc.CallOption) (*PdfResult, error)
}

type pdfComposeClient struct {
	cc grpc.ClientConnInterface
}

func NewPdfComposeClient(cc grpc.ClientConnInterface) PdfComposeClient {
	return &pdfComposeClient{cc}
}

func (c *pdfComposeClient) CreatePdf(ctx context.Context, in *Upfiles, opts ...grpc.CallOption) (*PdfResult, error) {
	out := new(PdfResult)
	err := c.cc.Invoke(ctx, "/pdfcompose.PdfCompose/CreatePdf", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PdfComposeServer is the server API for PdfCompose service.
// All implementations must embed UnimplementedPdfComposeServer
// for forward compatibility
type PdfComposeServer interface {
	CreatePdf(context.Context, *Upfiles) (*PdfResult, error)
	mustEmbedUnimplementedPdfComposeServer()
}

// UnimplementedPdfComposeServer must be embedded to have forward compatible implementations.
type UnimplementedPdfComposeServer struct {
}

func (UnimplementedPdfComposeServer) CreatePdf(context.Context, *Upfiles) (*PdfResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePdf not implemented")
}
func (UnimplementedPdfComposeServer) mustEmbedUnimplementedPdfComposeServer() {}

// UnsafePdfComposeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdfComposeServer will
// result in compilation errors.
type UnsafePdfComposeServer interface {
	mustEmbedUnimplementedPdfComposeServer()
}

func RegisterPdfComposeServer(s grpc.ServiceRegistrar, srv PdfComposeServer) {
	s.RegisterService(&PdfCompose_ServiceDesc, srv)
}

func _PdfCompose_CreatePdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Upfiles)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PdfComposeServer).CreatePdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pdfcompose.PdfCompose/CreatePdf",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PdfComposeServer).CreatePdf(ctx, req.(*Upfiles))
	}
	return interceptor(ctx, in, info, handler)
}

// PdfCompose_ServiceDesc is the grpc.ServiceDesc for PdfCompose service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdfCompose_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pdfcompose.PdfCompose",
	HandlerType: (*PdfComposeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePdf",
			Handler:    _PdfCompose_CreatePdf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/api/pdfcompose.proto",
}
